Patch

diff --git a/.github/workflows/release-linux.yml b/.github/workflows/release-linux.yml
--- a/.github/workflows/release-linux.yml
+++ b/.github/workflows/release-linux.yml
@@ -35,6 +35,11 @@ jobs:
             echo "Danser failed to build"
             exit 1
           fi
+
+          if [ ! -f "dist/artifacts/danser-${version// /-s}-linux.tar.xz" ]; then
+            echo "Danser tar.xz failed to build"
+            exit 1
+          fi
           echo "VERSION=$version" >> $GITHUB_ENV
 
       - name: Extract repository name
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -135,6 +135,11 @@ jobs:
             echo "Danser failed to build"
             exit 1
           fi
+
+          if [ ! -f "dist/artifacts/danser-${version// /-s}-linux.tar.xz" ]; then
+            echo "Danser tar.xz failed to build"
+            exit 1
+          fi
         id: build
 
       - name: Upload artifact
